### ISSUE TITLE
ONVIF events subscribe

### ISSUE THREAD

**Issue by ioKun** [beegee-tokyo/CCTVview#2]
Hi @beegee-tokyo!
Can you help to implement ONVIF events subscription?

**Comment by beegee-tokyo** [comment]
Not sure what you mean by ONVIF events.The cam I used is only partly ONVIF conform and I what I know is that you can send ONVIF commands to the cam and it gives you responses.

**Comment by ioKun** [comment]
ONVIF protocol has three type of event subscription (as described in this [answer](https://stackoverflow.com/questions/41589693/unable-to-implement-event-subscription-in-onvif))
So I'm want to implement second one **Basic Notification Interface.(Push Mechanism)**. 
In that case I try to use this kind of request (take it by wireshark from onvif desktop app)
```xml
                <s:Envelope
                xmlns:s="http://www.w3.org/2003/05/soap-envelope"
                xmlns:a="http://www.w3.org/2005/08/addressing">
                    <s:Header>
                        <a:Action>
                            http://docs.oasis-open.org/wsn/bw-2/NotificationProducer/SubscribeRequest
                        </a:Action>
                        <a:To>
                            http://192.168.0.239:8080/onvif/events
                        </a:To>
                    </s:Header>
                    <s:Body
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <Subscribe
                            xmlns="http://docs.oasis-open.org/wsn/b-2">
                            <ConsumerReference>
                                <a:Address>
                                    http://$ipv4ip:8085/subscription-1
                                </a:Address>
                            </ConsumerReference>
                            <InitialTerminationTime>
                                PT60S
                            </InitialTerminationTime>
                        </Subscribe>
                    </s:Body>
                </s:Envelope>
```
<a:Address> - adress of the Netty server running on my android device.

**Comment by beegee-tokyo** [comment]
Sorry, but I cannot help you. The only ONVIF camera I have is supporting only a very small part of the ONVIF standard, not even all ONVIF services nor ONVIF discovery. 
I never went farther than what you find in the code of this Android app.

**Comment by ioKun** [comment]
Thx for your response!)

**Comment by AdyRock** [comment]
> ONVIF protocol has three type of event subscription (as described in this [answer](https://stackoverflow.com/questions/41589693/unable-to-implement-event-subscription-in-onvif))
> So I'm want to implement second one **Basic Notification Interface.(Push Mechanism)**.
> In that case I try to use this kind of request (take it by wireshark from onvif desktop app)
> 
> ```
>                 <s:Envelope
>                 xmlns:s="http://www.w3.org/2003/05/soap-envelope"
>                 xmlns:a="http://www.w3.org/2005/08/addressing">
>                     <s:Header>
>                         <a:Action>
>                             http://docs.oasis-open.org/wsn/bw-2/NotificationProducer/SubscribeRequest
>                         </a:Action>
>                         <a:To>
>                             http://192.168.0.239:8080/onvif/events
>                         </a:To>
>                     </s:Header>
>                     <s:Body
>                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>                         xmlns:xsd="http://www.w3.org/2001/XMLSchema">
>                         <Subscribe
>                             xmlns="http://docs.oasis-open.org/wsn/b-2">
>                             <ConsumerReference>
>                                 <a:Address>
>                                     http://$ipv4ip:8085/subscription-1
>                                 </a:Address>
>                             </ConsumerReference>
>                             <InitialTerminationTime>
>                                 PT60S
>                             </InitialTerminationTime>
>                         </Subscribe>
>                     </s:Body>
>                 </s:Envelope>
> ```
> 
> <a:Address> - adress of the Netty server running on my android device.

Sorry to hijack this but I wanted to thank ioKun for posting the structure for this as I have been trying to work out the format and searching for days.

I don't suppose you have the same for the refresh request do you?

Best regards,
Adrian.

**Comment by beegee-tokyo** [comment]
I can just repeat my earlier comment:

> 
> Sorry, but I cannot help you. The only ONVIF camera I have is supporting only a very small part of the ONVIF standard, not even all ONVIF services nor ONVIF discovery.
> I never went farther than what you find in the code of this Android app.
