### ISSUE TITLE
Not found some import method

### ISSUE THREAD

**Issue by mintheinwin** [beegee-tokyo/CCTVview#3]
I try to use your sample code to watch stream video from IP camera.
I got error in findSPMbyMDNS class file 
import out found. 

import rx.Subscription;
import rx.Subscription;
import rx.android.schedulers.AndroidSchedulers;
import rx.functions.Action1;
import rx.schedulers.Schedulers;

which library get this import method.
Please help thanks

**Comment by beegee-tokyo** [comment]
Hello @mintheinwin 

I am sorry, the code is based on a 6 year old Android version. I didn't maintain it and it will most likely not work with the actual Android SDK anymore.
